
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    command: pm2-runtime ecosystem.config.js
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - .:/app:delegated  # Ensures better performance
      - /app/node_modules  # Prevents conflicts with host's node_modules
    environment:
      - NODE_ENV=production
    restart: always

